"""initial schema

Revision ID: cc92e7cc960e
Revises: 
Create Date: 2026-04-25 05:42:08.008344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc92e7cc960e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listing', 'source',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('copart', 'iaai', 'amerpol', 'auctiongate', 'manual', name='source'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listing', 'source',
               existing_type=sa.Enum('copart', 'iaai', 'amerpol', 'auctiongate', 'manual', name='source'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    # ### end Alembic commands ###
